version: '3'

services:

  mpiconsul:
    image: consul:latest
    ports: 
      - "81:8500"
    networks:
      - xebmpinet
    deploy:
      replicas: 1

  mpimaster:
    image: xebec/xebmpi-master:0.1
    volumes:
      - /swarm:/swarm
    ports:
      - "23:22"
    networks:
      - xebmpinet
    deploy:
      replicas: 1

  mpinode:
    image: xebec/xebmpi-node:0.1
    volumes:
    - /swarm:/swarm
    networks:
      - xebmpinet
    deploy:
      mode: global

networks:
   xebmpinet:
     driver: overlay
     internal: true
