version: '3'

services:

  mpiconsul:
    image: consul:latest
    ports: 
      - "81:8500"
    networks:
      - xebmpinet
    deploy:
      replicas: 1

  mpialice:
    image: xebec/xebmpi-alice:x64dev
    volumes:
      - /swarm:/swarm
    ports:
      - "23:22"
    networks:
      - xebmpinet
    deploy:
      replicas: 1

  mpidoll:
    image: xebec/xebmpi-doll:x64dev
    volumes:
    - /swarm:/swarm
    networks:
      - xebmpinet
    deploy:
      mode: global

networks:
   xebmpinet:
     driver: overlay
     internal: true
